# Site settings
title: Ninja Sài gòn
email: clgt@clgt.vn
description: "I-know-it-when-I-see-it"
keywords: "ninja saigon, nodejs, backbonejs, requirejs, sass, angularjs, reactjs, hướng dẫn, lập trình, cơ bản"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: ninja-saigon
github_username:  ninja-saigon
facebook_username:  ninja-saigon

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
