# Site settings
title: Js blog
email: clgt@clgt.vn
description: > # Welcome to my blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: unknown
github_username:  unknown

# Build settings
markdown: kramdown
