# Site settings
title: Ninja Sài gòn
email: clgt@clgt.vn
description: "Make your code cleaning"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: ninja-saigon
github_username:  ninja-saigon
facebook_username:  ninja-saigon

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
