# Site settings
title: Ninja Sài gòn
email: clgt@clgt.vn
description: "Make your code cleaning"
keywords: "ninja saigon, nodejs, backbonejs, requirejs, sass, angularjs, reactjs, hướng dẫn, lập trình, cơ bản"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: _mat_mun_
github_username:  vntrace
facebook_username:  dunghackem

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
